# Generated by Django 5.1.5 on 2025-02-03 13:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="full_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                default="Unknown", max_length=255, verbose_name="name"
            ),
        ),
    ]
